SuperDARN/pydarn

- pydarn/exceptions/rtp_exceptions.py
- pydarn/plotting/rtp.py
Before the `RTPUnkownParameter` would print:
```
pydarn.exceptions.rtp_exceptions.RTPUnknownParameter: Error: The following parameter was not found in the data set. Please make sure it is typed correctly or you are using the correct data.
```
Now it prints `RTPUnkownParameterError`:
```
pydarn.exceptions.rtp_exceptions.RTPUnknownParameterError: The following parameter p_l was not found in the data set. Please make sure it is typed correctly or you are using the correct data.
```
This error is thrown while generating summary plots for 20180903 unw due to the whole data set being partial records.
> fixed typo in RTPUnkownParameter

- pydarn/plotting/rtp.py
Was getting this error when concatenating 2-hour fitacf files and trying to plot the summary plots for each beam: 
```
Traceback (most recent call last):
File "pydarn_summary_plots.py", line 60, in <module>
plot_files(data, date, radar)
File "pydarn_summary_plots.py", line 41, in plot_files
pydarn.RTP.plot_summary(data, beam_num=beam)
File "/usr/lib/python3.6/site-packages/pydarn-0.1.dev0-py3.6.egg/pydarn/plotting/rtp.py", line 892, in plot_summary
background=background_color)
File "/usr/lib/python3.6/site-packages/pydarn-0.1.dev0-py3.6.egg/pydarn/plotting/rtp.py", line 302, in plot_range_time
dmap_record[parameter][j]
IndexError: index 75 is out of bounds for axis 0 with size 75
```
Realized the modes change the range gate values, so updated the code to search and find the max range gate …
> fixed a bug regarding getting max range gates from the data

- pydarn/plotting/rtp.py
As requested in #24 the new default parameter is `v` Velocity and the new default colormap is the PydDARN Velocity colormap. To keep with the majority of what users plot and with the velocity colormap convention. 
```
import pydarn
fitacf_file = "20180101.C0.cly.fitacf"
darn_read = pydarn.SDarnRead(fitacf_file)
fitacf_data = darn_read.read_fitacf()
pydarn.RTP.plot_range_time(fitacf_data, zmin=-600, zmax=600)
plt.show()
```
Granted this has one caveat with the other parameters:
However, they can change colormaps flexibly:
```
import pydarn
fitacf_file = "20180101.C0.cly.fitacf"
darn_read = pydarn.SDarnRead(fitacf_file)
fitacf_data = darn_read.read_fitacf()
pydarn.RTP.plot_range_time(fitacf_data, parameter='p_l', …
```
> changed default colormap and default parameter to velocity

- pydarn/plotting/fan.py
Instead of using the time from the first beam in the file, use the time of the first beam in the scan specified upon call to fan.py (scan_index).
> Time for MLT calculation

- pydarn/io/borealis/borealis.py
- pydarn/io/borealis/borealis_array.py
- pydarn/io/borealis/borealis_convert.py
- pydarn/io/borealis/borealis_site.py
- pydarn/io/dmap.py
- pydarn/io/superdarn.py
- setup.py
Package removed: pydarn/io
New location: [pyDARNio](https://github.com/superdarn/pyDARNio)
As discussed in the pyDARN dev meeting we are moving the pyDARN io out as it is it's own package and doesn't meet pyDARN's scope. 
```python
import pydarn
reader = pydarn.SDarnRead("20181220.1201.00.cly.rawacf")
data = reader.read_rawacf()
pydarn.ACF.plot_acfs(data, beam_num=5, gate_num=9,
start_time=datetime(2018, 12, 20, 12, 4)) 
plt.show()
```
**output**
```bash
/usr/local/lib/python3.6/dist-packages/pydarn-1.0.0-py3.6.egg/pydarn/io/superdarn.py: 319: PendingDeprecationWarning: SDarnRead method will be removed from pyDARN v 1.2, please use pyDARNio: https://github.com/SuperDARN/pyDARNio …
```
> Deprecation of IO package

- pydarn/__init__.py
- pydarn/utils/scan.py
**Scan formation**
**module:** *scan.py*
**package:** *pydarn/utils*
This PR adds rudimentary functionality to seperate a dmap_data list of libraries into scans, according to the scan flag specified within the records.
`build_scan` simply returns a 1D list with length equal to the number of dmap records, with an integer number indicating which scan each record is a part of. Initially this will be used for fan plots when merged, and so this functionality will be removed from PR #52. 
```python
import pydarn
file = "20200507.0.fitacf"
SDarn_read = pydarn.SDarnRead(file)
beam_scan=pydarn.build_scan(fitacf_data)
print(beam_scan)
>>array([  1.,   1.,   1., ..., 720., 720., 720.])
```
> Scan locating and labelling

- pydarn/__init__.py
- pydarn/plotting/rtp.py
- pydarn/utils/conversions.py
Feature: `gate2slant`
module: *conversions.py*
package: *utils*
This new feature converts range gates to slant ranges (km) brought up by trying to overlay PFISR (Poker Flat Incoherent Scatter Radar) data with KOD SuperDARN data. 
I based the code off of [DaVitpy slant range calculation](https://github.com/vtsuperdarn/davitpy/blob/f2c11e34f781ba5fd027b5ce789d39ff1f4f86f1/davitpy/pydarn/radar/radFov.py)
```python
import pydarn
import logging
#Load in dmap file
file = "20180220.C0.rkn.fitacf"
SDarn_read = pydarn.SDarnRead(file)
#Plot FOV and show
a = pydarn.RTP.plot_range_time(fitacf_data, beam_num=5)
#a = pydarn.RTP.plot_summary(fitacf_data, beam_num=5)
plt.show()
```
If you plot a Range-time Parameter plot you get:
If …
> NEW Feature: Slant Range

- pydarn/exceptions/radar_exceptions.py
This PR is to address Issue #66 it includes the location of where the hardware files are, if the error is on install make an issue on github and this library does not use RST for hardware files. With the updated hardware link. 
Test:
```python 
import pydarn
pydarn.read_hdw_file('zzz')
```
```bash
resetting environment variable AACGM_v2_DAT_PREFIX in python script
non-default coefficient files may be specified by running aacgmv2.wrapper.set_coeff_path before any other functions
Hardware file for zzz radar was not found in /usr/lib/python3.6/site-packages/pydarn-1.1.0-py3.6.egg/pydarn/utils/hdw/. Please ensure the abbreviation is correct and there exists a hardware file for it by checking: https://github.com/superdarn/hdw. If this error occurs when installing pydarn, please make an issue …
```
> Updating hardware exception

- pydarn/__init__.py
- pydarn/plotting/fan.py
fixing the following `Userwarning`:
`UserWarning: FixedFormatter should only be used together with FixedLocator` 
**issue**: #104 
**Number of approvals:** 1 this is a  1 liner fix
``` python
import pydarn
#Read in fitACF file
fitacf_file = "20100305.0001.00.inv.fitacf"
fitacf_data = pydarn.SuperDARNRead(fitacf_file).read_fitacf()
fanplot = pydarn.Fan.plot_fan(fitacf_data)
plt.show()
```
and no `userwarning`  message should appear
> fixed the warning message on fan plots

- pydarn/plotting/rtp.py
To fix issue #126 
Fix for the offset between the major and minor ticks when using the slant=True option for RTP and subsequently summary plots. The minor ticks are now set to be in the middle of the major ticks. Previous to this, the ticks were set at every 100, so they may look more sparse on the summary plots as there would have been 4 minor ticks between each major tick, and now there is just 1 minor tick.
I have also included a quick change to the major ticks so that they show up on the nearest hundred and increase each 200 for RTP (still increase at 500 on summary plots but are rounded to nearest hundred too, possible future change to make summary plots put ticks on the nearest 500th unit?), mainly for neatness and ease of the user to read off the axis.  …
> FIX/Offset between major and minor ticks using slant range in RTPs

- pydarn/plotting/fan.py
Fixes issue where a beam worth of data was dropped, and where the top arc of the radar FOV was plotted one range gate too low. Described in more detail in issue #139. 
```python
file='20170731.2202.00.inv.fitacf'
fanplot = pydarn.Fan.plot_fan(fitacf_data)
plt.show()	
```
Compared with current develop branch, one more beam of data should be visible on the rightmost portion of the FOV
> Fix for dropped beam in plot_fan and plot_fov

- pydarn/plotting/rtp.py
Amending so the data is plotted from the inner edge of the range gate not the center of the range gate when converted to slant range. 
To fix #132 
**Number of approvals:** 2 (only a one line fix so not hard)
```python
import pydarn
import logging
#Load in dmap file
file = ".fitacf" # any fitacf file here
#Plot FOV and show
a = pydarn.RTP.plot_range_time(fitacf_data, beam_num=4, slant=True)
#a = pydarn.RTP.plot_summary(fitacf_data, beam_num=2, slant=True)
plt.show()
```
Should notice that it begins plotting ~22.5km closer than it did before if on a 45km mode. (Rounded to int on axis though)
> [FIX] Plot RTPs from edge of range gate not center value

- pydarn/plotting/rtp.py
- pydarn/utils/conversions.py
Gets the Rx rise time using `SuperDARNRadars.radar[stid].hardware_info.rx_rise_time` in the `plot_range_time` function in `rtp.py` when plotting.
This value gets passed to `gate2slant` and that gets used as the rxrise variable in the calculation. 
An alternative would be to grab the rxrise from the hardware files inside the `gate2slant` function, however I had trouble importing `SuperDARNRadars` from `pydarn` in `conversions.py` and assumed as we already import it in `rtp.py` it would fit better there and give a wider range of use, allowing people to give inputs to `gate2slant` maybe down the line. This also allows us to set a default value of 0 if the Rx rise time is not given in the function call. 
Getting the Rx rise time from hardware was chosen as previous discrepancies exist between …
> FIX: Get rxrise from hdw

- pydarn/plotting/fan.py
This uses `SuperDARNRadars` to determine the hemisphere of the radar. 
**Number of approvals:** 1 - changed 1 line
```  python
import pydarn
pydarn.Fan.plot_fov(66, datetime(2021, 2, 5, 12, 5), ranges=[0, 75])
#pydarn.Fan.plot_fov(4, datetime(2021, 2, 5, 12, 5), ranges=[0, 75])
plt.show()
```
North
South
> EHN: Hemisphere  determination in Fan plots 

- pydarn/plotting/fan.py
Fan and FOV plots were plotting in geographic in develop branch, when they should be in AACGM coords. 
This was due to the old way of reading in which coordinate system you wanted (ie. coords = 'aacgm'), this has now been amended to read `coords=Coords.AACGM` and should plot in geomag coords now. 
This can be easily seen in the Inuvik radar plots, as Inuvik only skims the geographic north pole, but covers the geomagnetic north pole: see below diagrams. 
**issue:** NA
```python
#Read in fitACF file
file = "20150305.0601.00.inv.fitacf"
#Make the fan plot and show
pydarn.Fan.plot_fan(fitacf_data, scan_index=10, 
groundscatter=1, colorbar=True, parameter='v', 
colorbar_label='Velocity', …
```
> FIX: Function radar_fov call in plot_fov needed updating to use the new Coords.AACGM

- pydarn/__init__.py
- pydarn/plotting/axis.py
- pydarn/plotting/fan.py
- pydarn/utils/radar_pos.py
Remove the functionality of generating a default polar plot from each individual function which does it, placing it in it's own file called `axis.py`. This houses the polar plotting code `axis_polar`, accepting all normal options as kwargs from functions that call it.
Currently, only `plot_fan` and `plot_fov` benefits from this, but it will soon apply to `plot_grid` and any future "mapping" functions, like convection maps. `axis.py` will be further developed in the future so other types of projections, not just `axis_polar`, will be available. 
Currently, the only keywords which `axis_polar` accepts is `lowlat` and `hem` for the lower latitude boundary of the polar plot and the hemisphere, respectively. If no hemisphere is given, it works it out based on what radar is being plotted. 
- …
> Polar plots modularity

- pydarn/plotting/rtp.py
This bug fixes the over-the-coloring of ground scatter, sadly could not get grey into the plot as a legend but could look at that later. 
**issue:** #170 
**Number of approvals:** 1 simple fix
**matplotlib version**: 3.3.4
```
import pydarn
fitacf_file = './data/20150308.1400.03.cly.fitacf'
fitacf_data = pydarn.SuperDARNRead().read_dmap(fitacf_file)
pydarn.RTP.plot_range_time(fitacf_data, groundscatter=True, background='black', zmin=-200, zmax=200, beam_num=3, parameter='v')
plt.show()
```
`develop`
`fix/groundscatter`
> FIX: ground scatter bug

- pydarn/plotting/fan.py
Fixed the `scan_time` error by adding in at the top `scan_time=None` such that `scan_index=int` works. 
**issue:** #173 
**Number of approvals:** 1 - one line change
```python
import pydarn
pyk_file = 'data/20150308.1401.00.pyk.fitacf'
pyk_data = pydarn.SuperDARNRead().read_dmap(pyk_file)
pydarn.Fan.plot_fan(pyk_data, scan_index=2,
colorbar_label='Velocity [m/s]',
line_color='red', radar_label=True)
```
**matplotlib version**: 3.3.4
> [FIX] scan_index bug

- pydarn/utils/superdarn_radars.py
This fixes the Hemisphere and range gate value being swapped in `superDARNRadars`, seems like it was the only radar too. 
**issue:** #175 
**Number of approvals:** 1 - 1 line change
**matplotlib version**: 3.8.4
``` python
import pydarn
pydarn.Fan.plot_fov(209, datetime(2021, 2, 5, 12, 5), 
radar_label=True, line_color='blue')
pydarn.Fan.plot_fov(208, datetime(2021, 2, 5, 12, 5), 
radar_label=True, line_color='green')
plt.show()
```
> swapped the hemisphere and range gate value for ADW

- docs/user/fov.md
- pydarn/plotting/fan.py
- test/test_Fan.py
This PR adds the ability to plot all gate and beam boundaries on a FOV or Fan plot using the key word `grid`.
`grid` is defaulted to False, as it's a lot of lines and can look messy especially when plotting data. I have also set the inner lines to have 0.2 width, this seems to look a bit cleaner than the 0.5 lines because there are so many of them.
**issue:**  no linked issue, but mentioned in closed PR #183 
**Number of approvals:** 2 (test and code review)
**matplotlib version**:  3.4.2
pytest was run but not modified, no failures
Example of FOV plotting:
```python
import pydarn
fanplot=pydarn.Fan.plot_fov(66, datetime(2021, 2, 5, 12, 5), …
```
> EHN: Grid key word in FOV to plot the grid of gates and beams

- docs/user/fan.md
- docs/user/range_time.md
- pydarn/__init__.py
- pydarn/exceptions/plot_exceptions.py
- pydarn/exceptions/warning_formatting.py
- pydarn/plotting/fan.py
- test/test_Fan.py
This PR adds a keyword to the plot_fan method which allows the user to plot data from a single channel.
In addition, an exception has been made for when the user chooses a channel but it doesn't exist. 
A warning has also been made which warns that the data chosen has partial records: this is mainly due to the HAN and PYK radars running channels 1 and 2, but channel 2 only has partial records (CPID: 26999 'dummy channel'). But, the warning itself may be useful elsewhere down the line. 
The default will remain at `channel ='all'` which is the same as the RTP plots, and for the majority of cases 'all' will be fine and nothing will change- especially for the channels which are separated into files anyway. 
The main issue is that if you have files with multiple channel data, it may still try …
> EHN: Channel keyword for Fan plots

- pydarn/utils/radar_pos.py
- pydarn/utils/virtual_heights.py
- pydarn/utils/virtual_heights_types.py
This pull request enables pydarn with the modularization of virtual heights which include the standard virtual height and chisham virtual height. A new empirical virtual height model by G. Chisham 2008 (https://angeo.copernicus.org/articles/26/823/2008/)
```from pydarn.utils.virtual_heights_types import VH_types
from pydarn.utils.virtual_heights import standard_virtual_height, chisham
slant_range = 157.5
cell_height = 300
virtual_height_type = VH_types.CHISHAM
if virtual_height_type == VH_types.CHISHAM:
x_height = chisham(slant_range)
print(f"Chisham Virtual Height:{x_height}")
virtual_height_type = VH_types.STANDARD_VIRTUAL_HEIGHT    
if virtual_height_type == VH_types.STANDARD_VIRTUAL_HEIGHT:
x_height = standard_virtual_height(slant_range, cell_height) …
```
> Modularization of virtual heights

- .zenodo.json
- README.md
- docs/dev/communication.md
- docs/dev/issues.md
- docs/dev/releases.md
- docs/dev/team.md
- setup.py
This PR focuses on the following changes that will be released in v2.2:
- **New** Radar geographical Field-of-View (FOV) calculations functionality
- **Deprecation** Removed FOV files for radars geographic beam location
- **New** pytesting environment for testing pydarn for development
- **New** FOV grid lines to show range gates
- Bug fix in Range-time plots with groundscatter
- Bug fix in Range-time plots with time-shifting 
**issue:** #191 
**Number of approvals:** 3 approvals by **October 25, 2021**
Testing the following with the noted changes in the above list. 
Test the following with `grid=True`
> Release v2.2 

- setup.py
PR to make sure that when you update or install pydarn (or/and already have a version of pydarnio installed) that it will install version pydarnio 1.1.0 or up.
**issue:** to close #209 
**Number of approvals:** 2 (one liner but kinda complicated to test?)
**matplotlib version**: 3.3.4+ (NA)
So to test I've been:
1) making a virtual env 
`python3 -m virtualenv venv-testing-pydario-version`
`source venv-testing-pydario-version/bin/activate`
2) Install pydarn branch and dependencies 
`pip3 install git+https://github.com/superdarn/pydarn@BUG/pydarnio-version`
3) Downgrade pydarnio
`pip3 uninstall pydarnio`
`pip3 install pydarnio==1.0.0`
N.B. this will show you an warning `pydarn 2.2 requires pydarnio>=1.1.0, but you …
> FIX: Require pydarnio version 1.1.0

- pydarn/plotting/rtp.py
This PR is to fix the bug in issue 207. Summary plots and some range time plots were unable to be plotted.
I don't get Rems depreciation warning after making this change, I think that was fixed by the change to line 398 that occurred in the same commit pre-release (but would be good for Rem to re-check?).
**issue:** to close #207 
**Number of approvals:** 1/2 (one liner)
**matplotlib version**: 3.4.3
```python
import pydarn
#Load in dmap file
file = "/Users/carley/Documents/data/20211102.0000.00.rkn.a.fitacf"
a = pydarn.RTP.plot_summary(fitacf_data, beam_num=5, …
```
> FIX: Summary plot rendering bug

- pydarn/plotting/fan.py
Fixes the axes bug in `plot_fan` found by @ellioday
**issue:** #215 
**Number of approvals:** 1 - test simple fix 
**matplotlib version**: 3.3.4
``` python
import pydarn
import numpy as np
rkn_file = 'data/20180101.0000.01.rkn.fitacf'
fitacf_data = pydarn.SuperDARNRead().read_dmap(rkn_file)
fig = plt.figure(figsize=[6, 6]) 
ax = fig.add_gridspec(4, 20) 
ax1 = fig.add_subplot(ax[0:3,0:17], polar=True)
ax1.set_ylim(90, 40) 
ax1.set_xticks([0, np.radians(45), np.radians(90), np.radians(135),
np.radians(180), np.radians(225), np.radians(270),
np.radians(315), np.radians(360)])
ax1.set_xticklabels(['00', '03', '06', '09', '12', '15', '18', '21', '00']) …
```
> added axes to plot_fov call in plot_fab

- pydarn/plotting/fan.py
This PR is to fix the logic for setting ranges in the plot_fan method, the logic now checks if the user has entered it as an option in the call, if not then it grabs the number of ranges from the data file, if the data file is incomplete then it takes a default [0,75]. 
Rsep and frang should not be changed from default or from data read in as it invalidates the data so these are not keyword options for plot_fan method.
To fix the rsep and frang issues, they're already included in radar_fov, but are not used when called from plot_fov. So I've included them as keywords in plot_fov and when called from plot_fan will automatically plot the fov given by the rsep, frang and nrang in data (if ranges are not specified). You can effectively set the rsep and frang to anything you want in a call to …
> FIX: Misrepresentation of 15km data/Including frang and rsep in plot_fov call

- pydarn/plotting/fan.py
This PR fixes the bug where the FOV appears white in a small number of cases. A line in rtp.py sets bad values of a colormap to be white to fill in the background of the RTP/summary plots. If you plot a RTP and then a fan in the same program you would end up with the white background being carried over from being set in rtp.py. 
Setting the bad value to transparent makes the fan see-through again and doesn't interfere with any of the FOV kwargs as it's just transparent so you can see the FOV below. 
Other than forcing the transparency of the fan plot, is there a better way that we could be dealing with the cmap issue?
To see the difference you can compare this branch with current develop.
**issue:** NA but discussed in #242 
**Number of approvals:** 1 (one liner)
**matplotlib version**: …
> FIX: Bug where FOV in a fan plot is coloured white

- pydarn/plotting/maps.py
This PR adds the IMF clock angle on to the convection plots. 
There is not much in the way of customising it, but you can turn it off by setting 'imf_dial=False'.
As it is adding an additional axis to the plot, the user should be careful if adding to the plot later, as the gca will give the mini-axes for the dial rather than the larger plot. But I believe that specifying 'ax' will allow you to amend the main plot to your liking - please have a test of this if possible.
The actual axes size is twice the size of the plotted circle to allow for larger imf values to not be cut off - so bear that in mind when reviewing the values in the positioning of the annotations and sizing.
**issue:** to close #251 
**matplotlib version**: 3.5.1
**Note testers: please indicate …
> EHN: IMF Clock Angle Dial

- pydarn/plotting/maps.py
This PR adds requested map file info onto the map plot in the bottom left corner.
Currently included are: cross polar cap potential, number of vectors, fit order and model used. Let me know if any others are wanted, we can always do an extended optional version with all the lesser used values. 
**This will cause merge conflicts with the IMF dial, just make sure that the IMF dial is below this new code when sorting conflicts**
**issue:** to close #252 
**matplotlib version**: 3.5.1
```python
import pydarn
map_file = "/Users/carley/Documents/data/maps/20150310.n.map"
map_data = pydarn.SuperDARNRead().read_dmap(map_file) …
```
> EHN: Map Info on Convection Maps

- pydarn/plotting/maps.py
This PR fixes a bug in the contour plotting in convection maps. A TODO I left out was to add the mlon shifting to MLT out of the functions for plotting HMB and contours. It just so happened that the data we were all testing was generally from the same time of the day where the shift is minimal- but if testing in the early hours or late at night you can see the issue. 
**IF ANYONE HAS SOUTHERN HEMISPHERE MAP DATA PLEASE TEST ME!**
This will probably be required for the release branch as the release branch and develop right now are incorrect in plotting these two.
The vector plotting is all okay though!
**issue:** NA
**Number of approvals:** 2 please - to make sure it's scientifically correct
**matplotlib version**:  3.5.1 
**Note testers: please indicate what version of matplotlib you are …
> FIX: mlon shifting to MLT for HMB and contours

- pydarn/plotting/acf.py
This PR includes additions to the ACF plotting, as plots for phase and power of the ACF were requested along side. I've designed it similar to the Davit plots, but without the extra info that you get from fitacf.
The defaults have been changed to be un-normalized and for the power and phase to be plotted, but you can get the original by setting these to True and False respectively. 
I've also changed the logic a little so that the power plot does not get normalized. I've also added a return so the values of power and phase will be returned so the user can play around with them however they wish.
After discussions, we've found that the blanked lags are correct, so I've not done anything for that. We don't have the information to plot any extra lags (like the CRI bad lags) so we're leaving …
> EHN: Power and Phase Added to ACF Plots

- pydarn/plotting/rtp.py
- pydarn/utils/range_estimations.py
This PR adds an option to plot *HALF_SLANT* in fan plots and range time plots. Half slant is equal to *SLANT_RANGE* options divided by 2. This is considered better(?) than using GSMR option. 
https://doi.org/10.1029/2022RS007429
**issue:** #273 
**Number of approvals:** 2 please, lots of plotting testing
**matplotlib version**: 3.5.2
Summary plots:
```python
import pydarn
file = "/Users/carley/Documents/data/20131031.2201.00.sas.fitacf"
a = pydarn.RTP.plot_summary(fitacf_data, beam_num=2, range_estimation=pydarn.RangeEstimation.HALF_SLANT)
plt.show()
```
Gives: 
Fan plots (comparison with SLANT_RANGE): …
> New Feature: HALF_SLANT option for RangeEstimate

- pydarn/plotting/fan.py
This PR gives the groundscatter masked array a zorder of one above the full array of data for a fan plot. Previously the data was plotting over the groundscatter if groundscatter=True.
Develop branch now:
With this fix:
**issue:**
**Number of approvals:** 1, only a one liner.
**matplotlib version**: 3.5.3
```python
import pydarn
file='/Users/carley/Documents/data/20150308.1400.03.cly.fitacf'
pydarn.Fan.plot_fan(fitacf_data, scan_index=5, lowlat=50, groundscatter=False)
plt.show()
```
Gives the second plot above.
> BUG: Groundscatter fix for fan plots

- pydarn/plotting/maps.py
This PR speeds up the plotting of default convection maps when the user doesn't want FOV or radar locations (which is default).
If boundary (FOV) = False and radar_location=False then the code will now skip calling the plot_FOV function and call a basic projection to get the axes. If either are True, then it will call each FOV to plot individually as before. 
This removes ~13 seconds from the plotting time of one convection map, reducing the total time taken by 2/3, yay!
Using the coastline=True option will increase time taken, as its calling some Cartopy functions and then is converted to MLT, by 2 seconds. If coastlines=False, then the whole axis plotting is now only 0.1 seconds, making a vast improvement on speed. 
The remaining time taken (~6 seconds) is plotting the contours, …
> EHN: Speed up common use of convection maps

- pydarn/plotting/fan.py
- pydarn/plotting/grid.py
- pydarn/plotting/maps.py
- pydarn/plotting/rtp.py
This PR changes the colour bar plotting for rtp, fan, grid and map plots where the colour map does not extend below zero. 
This is done by having an if statement around the colour bar plotting, if the vmin of the data is == 0 then only extend the top of the bar, if not then have both extended. 
I have not changed the code for contour colour bar in maps as the contours will always be centred at 0 so extend both ways regardless. 
**issue:** No issue made
**matplotlib version**: 3.5.3
```python
import pydarn
file = "/Users/carley/Documents/data/20160120.1602.00.cly.fitacf"
a = …
```
> BUG: Fix for when colour bars should not be extended below zero

- pydarn/plotting/projections.py
This PR fixes the 'extents' of the geographic fan/grid plots so that the inputted lowlat value is used.
Also included is a fix for lowlat values for southern data. 
There is a known error in the Geographic grid plots when plotting multiple fans, please ignore for now that fix is out of scope for this PR, this fix is purely for the low latitude boundary.
**PLEASE ALSO NOTE THAT THE DIFFERENT PROJECTIONS DISPLAY DIFFERENTLY FOR SOUTHERN DATA**
Geographic projections will appear as if looking up at the South pole, polar projections will appear as if looking *through* the Earth from above to the South pole as is common for hemisphere comparisons - I have added this to the documentation issue to make sure it is stated somewhere. 
Map plots only use polar projection so this will not affect them …
> FIX: Geographic projection extents now tied to user inputted or default 'lowlat' value

- pydarn/plotting/maps.py
This fixes the depreciation of the axes_grid module of matplotlib -appears to have just changed to axes_grid1.
**issue:** #284 
**Number of approvals:** 1 (1 liner)
**matplotlib version**: tested on 3.6.0 (new version that won't work before), 3.5.3 and 3.3.4 (lowest compatible version with pyDARN)
imports correctly:
`import pydarn`
You can check that the map plots are still working with:
```python
import pydarn
map_file = "/Users/carley/Documents/data/maps/20170113.s.map"
map_data = pydarn.SuperDARNRead().read_dmap(map_file)
pydarn.Maps.plot_mapdata(map_data,record=360, 
parameter=pydarn.MapParams.FITTED_VELOCITY,
lowlat=30, color_vectors=False,
contour_fill=True, coastline=True) …
```
> FIX: mpl axes_grid depreciation fix

- pydarn/plotting/rtp.py
This PR removes some code that set ymax values to 75 range gates or equavalent in summary plots. *ymax* now works as a kwarg to read through to *plot_range_time* and the user can now set values of ymax for all range time plots. They all must be the same ymax value though. Not setting ymax will default to min/max values of the data as written in *plt_range_time*.
Be nice to get this into the current release branch too.
**issue:** to close #288 
**Number of approvals:** 1 is fine, 2 would be nice. Just removal of some code. 
**matplotlib version**: 3.6.2
```python
import pydarn
file = "/Users/carley/Documents/data/20160120.1602.00.cly.fitacf" …
```
> FIX: Remove *ymax* set values for summary plots

- pydarn/utils/superdarn_radars.py
This PR includes the new ICE and ICW radars. 
Will wait for merge in hdw repo and then will need to point the hdw link to a newer commit in the hdw repo, but this PR includes the changes needed in the code.
Considering waiting doing the patch release to include this update too, as it includes more changes in the hdw repo?
**issue:** close #300 
Can't test properly until the PR in hdw is merged. 
You can grab those files from the hdw repo and add them to your pydarn/utils/hdw directory if you wanted to test just these new lines of code, but we need to test the hdw repo commit anyway later.
hdw repo now contains ICE and ICW, I have updated the submodule, so will convert to ready!
Make sure when installing that you get the new hdw files in the correct directory, …
> EHN: Adding New Iceland Radars

- docs/user/fan.md
- docs/user/fov.md
- pydarn/plotting/fan.py
This PR contains an addition to the `fan.py` module that allows for the option `beam` to be passed to the fov and fan plotting functions. This allows the user to plot more specific data, or make diagrams with beams in fov.  The examples below use a file that is using camping beam,  which is a good use case/option to plot single beams. Default for `beam` is `None`. Docs updated. 
**issue:** #294 
**Number of approvals:** 2 test and code review
**matplotlib version**: 3.6.3
```python
import pydarn
file = "/Users/carley/Documents/data/20150308.1400.03.cly.fitacf"
_, _ , ax, ccrs = …
```
> EHN: Single Beam Options

- pydarn/plotting/grid.py
This PR fixes the bug where if a partial record is given to the grid plotting method, an error in the code will show instead of the warning about partial records. 
**issue:** to close #310 
```python
import pydarn
#grid_file = "/Users/carley/Documents/data/grids/20210101.0001.00.zho.grd"
grid_file = "/Users/carley/Documents/data/grids/20210101.0400.00.jme.grd"
grid_data = pydarn.SuperDARNRead(grid_file).read_grid()
print(grid_data[30])
pydarn.Grid.plot_grid(grid_data, record=30)
plt.show()
```
when running for the JME file you should find that the partial records warning shows, not an error:
```
pyDARN …
```
> FIX: Correct where partial record check occurs in Grid plot

- pydarn/plotting/rtp.py
This PR stops the code from hanging when plotting R-T plots on data that is slightly out of time order.
This issue was found with data from HOK for 2016-01-16 where two records are written for the same beam and channel with milliseconds difference, but some records saw that the first occurred after the second record. It's not in our remit to decide if these data should be in the distribution or not, I'm just fixing it so that a warning will show, and the summary plot will not hang trying to plot for 6 hours. 
In the future we should also have a discussion on what we want to do with warnings as for summary plots they are switched off and due to this I had to use a print statement instead of the warnings library for this warning- this is out of scope for this PR but something that needs …
> FIX: Bug in plotting when data out of time order

- pydarn/plotting/maps.py
This PR ensures that scatter points are not plotted below the clipped area of the map plot. 
This happened as the clip area was turned off to plot the reference vector.
**issue:** to close #308 
**Number of approvals:** 1 pretty simple change
**matplotlib version**: 3.5.3
```python
import pydarn
#map_file = "/Users/carley/Desktop/test/20200101.n.map"
map_file = "/Users/carley/Documents/data/maps/20130531.n.map"
#map_file = "/Users/carley/Documents/data/maps/20190421.s.map2"
map_data = pydarn.SuperDARNRead().read_dmap(map_file)
plt.figure(figsize=(8,6))
pydarn.Maps.plot_mapdata(map_data,record=690, 
parameter=pydarn.MapParams.FITTED_VELOCITY,
lowlat=60, contour_fill = False, …
```
> FIX: Lowlat scatter was not clipped on Maps

- pydarn/plotting/color_maps.py
- pydarn/plotting/fan.py
- pydarn/plotting/grid.py
- pydarn/plotting/maps.py
- pydarn/plotting/projections.py
- pydarn/plotting/rtp.py
This is a simple change of default colormap for the elevation data in rtp and fan plots.
EDIT: Whilst doing this change, Rem noticed a depreciation for cm.get_cmap which is not backwards compatible with older matplotlib versions. As a lot of servers cannot get the newer matplotlib versions I have left in a conditional import for the colormaps. To make this easier I have move any colormap 'get' processing to the color_maps.py module so that we only have to do one conditional import for cm/colormaps.
**issue:** #323 
**Number of approvals:** 1 (Probably 2 now with changes)(and the okay from Bharat for this change next meeting!)
Plot RTP/Summary and fan plots.
Make sure grids show up on …
> EHN: Elevation Default to 'inferno' and Fix `cm.get_cmap` Depreciation

- pydarn/io/superdarn_io.py
This PR will allow read_dmap to read in without issue any DMap formatted file. Some files fail checks when using read_fitacf etc. but can possibly still be plotted as the data required for plotting is there. This is obviously something up to the discretion of the user, and as default we will tell people to use the read_filetype version of reading primarily.
**issue:** No issue made
```python
import pydarn
fit_file = "/Users/carley/Documents/data/20180101.0000.01.rkn.fitacf"
fit_data = pydarn.SuperDARNRead(fit_file).read_fitacf()
print(fit_data[0].keys())
fit_data2 = pydarn.SuperDARNRead(fit_file).read_dmap(fit_file)
print(fit_data2[0].keys())
raw_file = …
```
> DEP: Removed checks when using read_dmap

- pydarn/plotting/rtp.py
This PR changes the default Nave line in summary plots to be blue. Watermark is now default off. 
**issue:** #324 
Test watermark=True as well.
```python
import pydarn
file = "/Users/carley/Documents/data/20211102.0000.00.rkn.a.fitacf"
a = pydarn.RTP.plot_summary(fitacf_data , beam_num=13)
plt.show()
```
Gives:
> EHN: Summary plot defaults - change default Nave line to blue and watermark to False

- pydarn/plotting/rtp.py
- pydarn/utils/range_estimations.py
This pull request replaces the current equation to calculate the GSMR range estimate, and makes a new method for GSMR_BRISTOW which uses the older Bristow GSMR version.
There is also a new warning when inf values are found during the Bristow equation method. 
You can read the discussion of this issue at #257
**issue:** to close #257 
```python
import pydarn
file = "/Users/carley/Documents/data/20211102.0000.00.rkn.a.fitacf"
a = pydarn.RTP.plot_summary(fitacf_data, beam_num=2, range_estimation=pydarn.RangeEstimation.GSMR, watermark=False, title='New …
```
> EHN: Replace GSMR equation

- pydarn/plotting/fan.py
- pydarn/utils/coordinates.py
- pydarn/utils/range_estimations.py
This PR changes the calculation for geographic coordinates of the location of each range gate to include the 'offset' value of boresight from hdw files, and removes the abs() function from bmsep calculation to allow for the correct beam numbers. 
As the abs() was originally a bug fix for a colouring-in issue with cartopy plots, this is now taken care of inside the fov method rather than in the position calculation using an if statement. 
**issue:** #351 
**Number of approvals:** 2 with a quick code review if possible
You can plot all the FOV in geographic coordinates, this should colour in the FOv in grey, anything outside should not be shaded:
```python
import pydarn
from datetime …
```
> BUG: Corrections converting gate to geographic location

- pydarn/plotting/acf.py
* Changed all classmethods to staticmethods
* Created staticmethod plot_acf_param() to handle plotting of values, which is called within plot_acfs() as needed to plot real, imaginary, power, and phase of ACF
* Return all axes from plot_acfs() as list
* Plot real and imaginary ACF values on input ax to plot_acfs() if pwr_and_phs False, otherwise use plt.gca()
* Removed some unnecessary internal variables in plot_acfs().
* Proper handling of markers for blanked lags, taking into consideration if marker is a filled marker or not
**issue:** N/A
**Number of approvals:** *1*
Try running the tutorial from https://pydarn.readthedocs.io/en/main/user/acf/, and using as many of the optional arguments as you can.
> Major refactor of acf.py

- pydarn/plotting/rtp.py
- pydarn/utils/coordinates.py
- pydarn/utils/range_estimations.py
New range estimation variant, using time of flight.
**issue:** #348 
**Number of approvals:** *1*
Try this modified snippet from the summary plotting tutorial https://pydarn.readthedocs.io/en/main/user/summary/
```python3
import pydarn
fitacf_file = "20190831.C0.cly.fitacf"
darn_read = pydarn.SuperDARNRead(fitacf_file)
fitacf_data = darn_read.read_fitacf()
pydarn.RTP.plot_summary(fitacf_data, beam_num=2,
range_estimation=pydarn.RangeEstimation.TIME_OF_FLIGHT)
plt.show()
```
> New time of flight range estimation

- pydarn/plotting/maps.py
This PR implements a new method `calulate_potentials_pos()` for calculating the electric potentials at any given magnetic latitude and magnetic longitude. The code is mostly ripped from `calculate_potentials()`, but adjusted slightly / cleaned up so that there is no pre-defined grid (for plotting), and so that mlat/mlon can be given as inputs. 
2
```python
import pydarn
mapfile = '20230123.n.map'
#This example keeps mlon the same but changes mlat, like a keogram
mlats = [75, 76, 77, 78] 
mlons = [110, 110, 110, 110]
fit_coefficient = map_data[0]['N+2']
fit_order = map_data[0]['fit.order']
lat_shift = map_data[0]['lat.shft']
lon_shift = map_data[0]['lon.shft']
lat_min = map_data[0]['latmin']
hemisphere = …
```
> Calculating potentials at any coordinate

- pydarn/plotting/rtp.py
Allow manual specification of background transparency in RTP plots. This enables overplotting, so that the same axis can have multiple RTP plots on it.
**issue:** N/A
Try to plot call RTP.plot_range_time() with different data on the same axis object. On develop, it will hide the data from the first call. On this branch, you should be able to see the data behind.
> Allow user to specify background transparency in RTP calls.

- pydarn/plotting/maps.py
This is a really small change to fix the alpha in the map potential colour bar. The `mappable` object created for the colour bar doesn't preserve the alpha used when using `plt.contourf()`. This change adds it in.
Current behaviour:
Fixed behaviour:
**issue:**
1
```python
import pydarn
mapfile = '20221130.n.map'
record = dt.datetime(2022, 11, 30, 15, 0)
pydarn.Maps.plot_mapdata(map_data, start_time=record, lowlat=50, coastline=True, contour_fill=True, color_vectors=False)
```
> Add alpha to plt.colorbar when using pyplot.contourf

- pydarn/plotting/maps.py
Setting `map_info=False` when using `plot_mapdata()` didn't work previously because it would cause parameters (like the number of points and the cross-polar-cap potential) to not be stored into variables, causing the code to break at the return statement. This PR fixes the keyword when set to False by only checking it after those values are stored in variables. I also added `map_info` to the docstring, because it wasn't there before.
1
```python
import pydarn
mapfile = '20231004.n.map'
pydarn.Maps.plot_mapdata(map_data, record=0, lowlat=50, map_info=False)
plt.show()
```
Gives:
> Fixed `map_info=False` not working

- pydarn/plotting/maps.py
Small PR to clean up the docstring in `calculated_fitted_velocities()`, and remove the `len_factor' input which isn't used anywhere in the function (probably a holdover from this code was in `plot_mapdata()'. The datatypes for `mlats`, `mlons`, and `fit_coefficient` were changed to arrays from lists, because the code doesn't actually work if you give it a list.
```python
import pydarn
import numpy as np
mapfile = 'path/to/mapfile'
record = map_data[0]  # first record of the file
mlats = np.array([60,70,80])
mlons = np.array([-120,-120,-120])
fit_coefficient = record['N+2']
fit_order = record['fit.order']
lat_shift = record['lat.shft']
lon_shift = record['lon.shft']
lat_min = …
```
> Change input types, remove len_factor from calculated_fitted_velocities()

- docs/user/map.md
- pydarn/plotting/maps.py
This is a very small PR which fixes the behaviour of colourbars when making a convection map. Previously, setting `colorbar=False` when using `plot_mapdata()` would not work if `contour_fill=True`. This is because `plot_potential_contours()` uses a different keyword to control the colourbar for contours, and the one used in `plot_mapdata()` only controls the velocity colourbar.
This PR adds a second keyword to control the potential contour colourbar, `contour_colorbar`, which is set to False as default.
1
```python
import pydarn
mapfile = '20231004.n.map'
pydarn.Maps.plot_mapdata(map_data, record=0, lowlat=50, coastline=True, contour_fill=True, color_vectors=False, colorbar=False, …
```
> Fix colourbar preference not being preserved

- pydarn/plotting/maps.py
This PR amends the lowlat default in calculate_potentials to 30 (which is the default from projections) from 60.
**issue:** #376 
**Number of approvals:** 1, 1 liner
**matplotlib version**:  3.8.2
```python
import pydarn
map_file='data/maps/20220101.n.map'
map_data = pydarn.SuperDARNRead(map_file).read_map()
pydarn.Maps.plot_mapdata(map_data,record=521, 
parameter=pydarn.MapParams.FITTED_VELOCITY,
lowlat=50, contour_fill=True, reference_vector=250,
color_vectors=False, coastline=True)
plt.show()
```
Try different and no lowlat kw values - make sure that the contours fill the selected area you have chosen to plot.
> FIX: lowlat default value in maps set to 30

- pydarn/plotting/color_maps.py
- setup.cfg
This PR increases the required version of matplotlib from 3.3.4 to 3.5.0 due to the change of the colormap module in matplotlib. (I did the fix for this when 3.6.0 came out with the depreciation warning for the color_maps module but didn't change the rtp module, or maybe that was developed later I'm not sure. Anyway,  I don't think we need to have more complicated imports, we can just up the requirements as the version required is nearly 3 years old anyway)
Note that the cm library is still in use elsewhere for other purposes and only 'colormaps' was depreciated and moved from cm.
**issue:** #373 
**matplotlib version**: 3.5.0, 3.4.2, 3.8.3
Install pydarn as you would normally, you can …
> FIX: Increase matplotlib version requirement

- pydarn/plotting/projections.py
This PR changes `geo_coastline_to_mag()` so it works on geometry arrays, rather than iterating over each glat/glon pair individually, when converting to AACGM. The result is a significant speedup.
Taken from https://pydarn.readthedocs.io/en/main/user/fan/, but can be used in any projection where `coastline=True` and Cartopy is installed.
```python
import pydarn
file = "path/to/fitacf/file"
pydarn.Fan.plot_fan(fitacf_data,
scan_index=1, lowlat=60, zmin=-1000, zmax=1000,
boundary=True, radar_label=True,
groundscatter=True, ball_and_stick=True, len_factor=300,
coastline=True, parameter="v")
plt.show()
```
> Faster coastline coordinate conversion

- pydarn/utils/superdarn_radars.py
This PR includes an update to the submodule hdw to get the new hdw files.
Inclusion of SZE, SZW, HJE, HJW, LJE and LJW to the radars dictionary for information not included in hdw files. 
**issue:** will close #365 
**matplotlib version**: 3.8.2
**MAKE SURE THE HDW REPO IN utils/hdw CONTAINS THE NEW HDW FILES ON INSTALLATION OF THIS BRANCH**
We can plot the FOV for now:
```python
import pydarn
stids = [51,52,53,54,55,56]
cols = ['salmon','salmon','gold','gold','cornflowerblue','cornflowerblue']
plt.figure(figsize=(8, 8))
rtn=pydarn.Fan.plot_fov(stids[0], datetime(2021, 2, 5, 18, 5),
fov_color= cols[0],radar_location=True, …
```
> EHN: Addition of NSSC Radars

- pydarn/plotting/fan.py
- pydarn/plotting/grid.py
- pydarn/plotting/maps.py
- pydarn/plotting/projections.py
This PR amends some details in the projections module, updates the geographic plotting to allow the user to zoom in on areas and move the focus of the plot. A new projection is also made for the same thing in geomagnetic/MLT coordinates.
I was unable to allow subplot usage with these plots - the projections are very specific for use with SuperDARN data so I don't recommend making your own axes to put in, it would be nice to have the ability to plot multiple plots on one figure, but that will require a lot of work that I can't do right now.
Zoomable convection map plots will come eventually - they're just very hard and there are a few issues I haven't solved yet so that will all be in another PR at a later date!
Whats new:
- New MAG projection: I've absolutely shredded cartopy to make this …
> REF: Axes handling for projections - new geomagnetic zoomable plotting

- pydarn/plotting/rtp.py
This PR replaces the plot_date function in time series plots with the recommended plot function as plot_date is just a wrapper with a formatting input for dates. We don't use timezones so there should be no issues there. 
https://matplotlib.org/stable/api/_as_gen/matplotlib.pyplot.plot_date.html
**issue:** to close #393 
**matplotlib version**:  3.7.0 - 3.9.1
Testers please test with a few matplotlib versions. 
You can plot any time_series or summary plots to check - you should see no difference between develop and this branch except there is no deprecation notice for matplotlib 3.9+.
```python
a = pydarn.RTP.plot_time_series(fitacf_data, beam_num=5)
plt.show()
a = …
```
> DEP: Matplotlib plot_date deprecation

- pydarn/plotting/fan.py
This pull request hopes to give an option to anyone who needs more flexibility to the fan plots. You can essentially plot whatever data you want at any time for any radar, given you can make the data be in the right format. 
You will need to make a 2D list of data that matches the FOV of the target radar, where no data is given as NaN values, data is given as a float, and an array of 0,1 in the same dimensions will act as groundscatter with the dimensions [ranges, beams].
**issue:** to close #387 
**matplotlib version**: 3.9.1
Note: If you come across an error that traces back to numpy or pydarnio, please downgrade numpy, it is out of scope of pyDARN to fix this. 
There will also likely …
> EHN: Fan Plot using User Input Data

- pydarn/plotting/fan.py
- pydarn/plotting/maps.py
- pydarn/utils/plotting.py
This PR includes the addition of a time series plot option for plotting the potential calculated at a specific mlon, mlat in a map potential.
**issue:** to close #368 
**matplotlib version**: 3.9.1
NOTE THERE IS A NUMPY BUG IN PYDARNIO, DOWNGRADE NUMPY TO 1.26.4 OR BELOW, PLEASE TEST IN A VIRTUAL ENVIRONMENT. This is out of scope for pyDARN and will be fixed in pyDARNio later.  
``` python
import pydarn
mapfile = '/Users/carley/Documents/data/maps/20220101.n.map'
#This example keeps mlon the same but changes mlat, like a keogram
mlats = 75
mlons = 110 …
```
> NEW: Map Potential Time Series at Given MLON/MLAT

- pydarn/plotting/rtp.py
Following on from #399 
Integrated code into the summary plot method to allow user to print a subset of the allowed vector parameters (user requested)
**matplotlib version**: 3.9.1
```python
import pydarn
files = ["/Users/carley/Documents/data/20211102.0000.00.rkn.a.fitacf",
"/Users/carley/Documents/data/20231122.0402.00.fhe.fitacf"]
for file in files:
a = pydarn.RTP.plot_summary(fitacf_data, beam_num=5, vector_parameters='v')
plt.show()
#a = pydarn.RTP.plot_summary(fitacf_data, beam_num=5, vector_parameters=['elv', 'vel'])
#plt.show()
a = …
```
> EHN: Flexibility on Plotting Summary Plot Variables

- pydarn/plotting/maps.py
Fix when installing pydarn with matplotlib v3.10
**issue:** #410 
**matplotlib version**: 3.10
Import pydarn and plot a map file **including** the IMF dial (does so by default).
> Replaced deprecated `InsetPosition` import and usage.

- pydarn/plotting/rtp.py
Fixes calls to `np.zeros()` that did not pass shape correctly.
**issue:** #404 
**matplotlib version**: 3.9.2
Use `pydarn.RTP.plot_range_time()` and `pydarn.RTP.plot_coord_time()` with data that has a gap longer than 2 minutes in the middle.
> Fixed improper invocation of np.zeros()

- pydarn/utils/superdarn_radars.py
Was failing if hdw/ directory not present - simply added a line to make the directory if not present.
**issue:** #410 
Pull this branch, delete the hdw/ dir, then try importing pydarn from a Python session and confirm that it works.
> Fix fetching of hdw files.
