SuperDARN/pydarn

- pydarn/__init__.py
- pydarn/utils/conversions.py
- test/test_utils/test_conversions.py
Here is a smaller PR for review. Made some conversion functions to convert dmap records to dictionaries and vice versa. Might make the other PR easier to test as well. 
Fundamental functionality, further development will be to make SuperDARN specific conversion tools that cast the fields data to the correct types since python has some interesting caveats with data types. 
Also creating these functions to help with plotting functions.
> Conversion functions

- docs/index.md
- docs/user/citing.md
- mkdocs.yml
As pyDARN is two PR's away (this one and #33 ) from a release branch being created then released, I thought I would add a section on how to cite pyDARN as well SuperDARN. 
Please review your name in the citation BibTeX and thumbs up it if you are okay with your name's initials.
This PR will not stay open long after someone approves it so please give it a glance.
> Citing pyDARN

- setup.py
Fixed the bug with the sub repo not getting the most recent master changes. Please review this PR before #45 as this may change those subrepo commits I did. Sorry about that!  
Test: 
Install pydarn from this branch
```bash
cd pydarn/utils/hdw
ls 
```
you should see the hardware file for DCN and JME :p
> FIX - sub repo bug

- .github/PULL_REQUEST_TEMPLATE/bug_fix_template.md
- .github/PULL_REQUEST_TEMPLATE/deprecation_template.md
- .github/PULL_REQUEST_TEMPLATE/documentation_template.md
- .github/PULL_REQUEST_TEMPLATE/feature_template.md
- pydarn/__init__.py
I made some PR templates to help with user testing and developers to remember some checks and provide the right amount of information. 
Unfortunately, I created this branch off develop which is a bit ahead of the master so testing the templates will have to wait for a minor release, or maybe I can make a patch release soon.  
Anyways have a look and please provide some feedback!
> PR templates

- .zenodo.json
Hey everyone, here is the draft for zenodo authorship for pyDARN release 1.2 Hopefully soon. 
I based this on who has done the following: 
- tested
- submitted ideas 
- developed 
- reviewed code 
In the future, we may want to discuss how to ensure we aren't bloating the list if people stop helping out. 
I would also like to keep the publishing standard of the top 2 developers to get author/co-author and the rest are alphabetic. These top developers may be expanded as it is hard to know who committed the most :p
> adding zenodo json file for author names

- README.md
- pydarn/exceptions/plot_exceptions.py
- pydarn/exceptions/rtp_exceptions.py
- pydarn/exceptions/warning_formatting.py
- pydarn/io/superdarn_io.py
- pydarn/plotting/acf.py
- pydarn/plotting/fan.py
- pydarn/plotting/power.py
- pydarn/plotting/rtp.py
- pydarn/utils/conversions.py
- pydarn/utils/radar_pos.py
- pydarn/utils/scan.py
- pydarn/utils/superdarn_radars.py
- setup.py
PATCH release for the bug that hides data due to use white gate color for no value data. 
The fix was making it transparent and was purposed originally by @SEC-VT
**Number of approvals:** Approval from @billetd 
**WARNING** This is a hot fix so it will be going to master and have its own PATCH release due to it being a major bug. 
Please see #100 for test code
> added patch fix based on SEC-VT fix for white gates

- pydarn/plotting/grid.py
Just like  #106 I added so it can plot multiple radars values in a `GRD` file 
**Number of approvals:** 2 - 1 reviewer, 1  tester
```python
import pydarn
#Read in fitACF file
grid_file = "20100305.n.grd"
grid_data = pydarn.SuperDARNRead(grid_file).read_grid()
pydarn.Grid.plot_grid(grid_data)
plt.show()
```
To make  GRD  files you need RST:
```
combine_grd 20100305.inv.grid 20100305.pyk.grid 20100305.rkn.grid 20100305.sas.grid 20100305.wal.grid >  20100305.n.grd
```
I also have files if you need some
> [EHN] Multi Grid plotting

- pydarn/__init__.py
- pydarn/plotting/fan.py
Resolving the FOV being too small for grid plotting 
**issue**: #116
**Number of approvals:** 1 approval easy fix
```
import pydarn
#Read in fitACF file
grid_file = "20170729.0202.00.fhw.grid"
grid_data = pydarn.SuperDARNRead(grid_file).read_grid()
pydarn.Grid.plot_grid(grid_data)
plt.show()
```
> fixed the gate range default

- docs/dev/releases.md
- docs/index.md
- mkdocs.yml
Describes the process one has to take to make a release in pyDARN
> [Docs] pyDARN Release Guidelines

- pydarn/__init__.py
- pydarn/utils/constants.py
- pydarn/utils/conversions.py
This file makes a  constants fille so  we share  the same constants across pyDARN 
More of a review may be test slant range. 
``` python
import pydarn
import pydarnio
fitacf_file = './data/20210205.1200.00.cly.a.fitacf'
fitacf_data = pydarn.SuperDARNRead().read_dmap(fitacf_file)
pydarn.RTP.plot_range_time(fitacf_data, beam_num=7)
plt.show()
```
> added costants file

- pydarn/__init__.py
- pydarn/plotting/rtp.py
- pydarn/utils/coordinates.py
- pydarn/utils/radar_pos.py
Added two new coordinates AACGM and GEO and changed the name to aid in #151 and #149 
Testing rtp plotting
> [EHN] Coordinates 

- pydarn/plotting/fan.py
This PR creates titles for fan plots 
**issue:**
**Number of approvals:** 1 super easy
``` python 
import pydarn
fitacf_file = 'data/20210205.1200.00.cly.a.fitacf'
fitacf_data = pydarn.SuperDARNRead().read_dmap(fitacf_file)
pydarn.Fan.plot_fan(fitacf_data, scan_index=10)
plt.show()
```
> added title functionality

- pydarn/plotting/fan.py
This removes the double for loop to plot data with `pcolormesh` and fixes the cyclic coloring issue. 
**issue:** #143 
**Number of approvals:** 2 approvals - 1 review and 1 tester 
``` python
import pydarn
fitacf_file = 'data/20210205.1200.00.cly.a.fitacf'
fitacf_data = pydarn.SuperDARNRead().read_dmap(fitacf_file)
pydarn.Fan.plot_fan(fitacf_data, scan_index=datetime(2021, 2, 5, 12, 5)) 
plt.show()       
```
Note if you run the same code on `develop` you will notice for this fille it has coloring issues with cyclic:
> EHN: Fan pcolormesh

- pydarn/plotting/fan.py
This PR adds the functionality to FOV and Fan plots to be able to add a dot at the radar site and add a label near that site of the abbreviation of the radar name. 
The radar dot is positioned at the location of the radar from hardware files. 
The radar label is positioned slightly lower in latitude than the radar position - this is not perfect, colocated radars overlap and sometimes the labels overlap with the axes etc etc. 
The solution would be to hard code in an 'ideal' position for each radar (possibly in the SuperDARNRadar's class?) - the issue there is then how far does that go, do we then hard code values for each radar for each different map projection we might use in the future? It's very easy to add your own labels after the fact as a user, so as a standard default use I don't …
> EHN: Radar Position Dots and Labels

- docs/dev/PR.md
- docs/dev/branching.md
- docs/dev/pytest.md
- docs/index.md
- mkdocs.yml
Documentation on unit testing in pyDARN using pytest.
**Number of approvals:** 1-2 proof reading
https://pydarn.readthedocs.io/en/ehn-update_docs_with_ptest/
> [Doc] pytest documentation

- pydarn/plotting/fan.py
- pydarn/plotting/maps.py
This PR aims to solve the bugs caused by two branches being merged into develop at similar times. 
The first bug is the accidental removal of the `boundary` key word use in plot_fov/
The second bug is the changes to the variable return order for plot_fov which breaks the new maps.py plotting.
I've also removed the second citation warning that we don't need now it shows up on import. 
If anyone finds some other bugs due to this 'double merge' let me know and I can fix it in this PR.
**issue:** to close #231 
**Number of approvals:** 2 please
**matplotlib version**: 3.5.1
both can be tested using maps, boundary True or False, the fact it plots at all means the second fix works:
```python
import matplotlib.pyplot as …
```
> FIX: plot_fan variable return order changes and boundary option redo

- pydarn/plotting/projections.py
This PR adds the keyword and option to include coastlines within the projections.py module. This allows all of the plotting modules to access the option and neatly keeps all the cartopy use within one module.  Default is set to coastline=False. similar to the draft PR for convection maps, there is little we can do to customise the coastlines.
**issue:** #248 (I think this solves this issue, but there might be other functions included for this)
Please test for Fan, FOV, Grid and Convection plots!  Fan and FOV will plot coastlines for both Coords.GEOGRAPHIC and Coords.AACGM_MLT, grid and convection maps are only offered in MLT at the moment. Don't forget to test for southern data too!
**matplotlib version**: 3.5.2
**Note testers: please indicate what version of …
> EHN: Coastline options for Fan, FOV, Grid and Convection in projections.py

- pydarn/plotting/grid.py
This PR refactors the grid.py plotting code to include the option to plot in geographic coordinates. 
I personally wasn't going to do geographic for convection maps as no one really has asked for it and I don't need it, but this might be worth discussing more at the next meeting.
This branch is branched from current develop so some bugs are fixed in other PRs (like the colorbar extending below 0 when it shouldn't)
You may also note from the branch name that I was originally trying to fix a bug from #238 but then ended up with this fix instead. I'll keep going with the matplotlib axes, but it might just be an issue we can't resolve. It is possible to overplot fan and fov plots in any coords/projs, you just need to correct ax/ccrs read in which I will write up to docs. 
**issue:** to close …
> EHN: Grid plots in Geographic Coordinates

- pydarn/plotting/projections.py
The descriptions for both functions making the polar axis objects were incorrect (they were copy-pasted from `plot_fov`). This PR gives them an actual description. 
**Number of approvals:** *1*
> Fixed function descriptions in projections.py

- pydarn/__init__.py
- pydarn/plotting/maps.py
- pydarn/utils/plotting.py
Adds a method that graphs some map file parameters in time. Currently added are the number of vectors, IMF By/Bz magnitudes, KP index, and maximum HMB latitude. 
I'm having issues with getting the correct record index from an input datetime object, so I left it unimplemented for now. 
Implements issue #334 
0 approvals, needs 2
**matplotlib version**:  3.7.1
```python
import bz2 
import pydarn
file_path = "example_data/20150310.north.map2.bz2"
data = pydarn.SuperDARNRead().read_dmap(file_path)
pydarn.Maps.plot_time_series(data, parameter=pydarn.Maps.TimeSeriesParams.NUM_VECTORS,
start_record=0, end_record=100)
plt.show()
```
> Feature: Time Series Plots from Map files

- pydarn/plotting/maps.py
This PR is a continuation of #335 but I'm still learning how to use the CLI so it made a new branch!
See over on that PR for testing details, but test this branch not Nathaniels forked branch! Thanks :D
**issue:** None
> EHN: Setting contour levels in Maps

- pydarn/plotting/maps.py
**issue:** This pull request lets the user manually specify the vmin and vmax values for the map potential contour colorbars.
*provide a list or code to test*
```
import bz2
import pydarn
import pydarnio
map_file = "20220202.north.map2.bz2"
with bz2.open(map_file) as fp:
dmap_stream = fp.read()
reader    = pydarnio.SDarnRead(dmap_stream, True)
map_data  = reader.read_map()
pydarn.Maps.plot_mapdata(map_data, record=150, 
parameter=pydarn.MapParams.FITTED_VELOCITY,
lowlat=40, colorbar_label='Velocity m/s',
contour_fill = True,
contour_fill_cmap= 'RdBu',
contour_colorbar = True,
contour_colorbar_label='Potential (kV)', …
```
> expose potential vmin vmax

- pydarn/__init__.py
- pydarn/plotting/fan.py
- pydarn/plotting/projections.py
- pydarn/utils/scan.py
* Changed projections.py so that a user can pass in an already-defined axis with a projection
* Changed scan.py to find records in a scan by either scan index or datetime
* Refactored fan.py to incorporate the above changes, and allow user to pass in axis object to plot colorbar in.
* Refactored all methods in fan.py to staticmethods
**issue:** N/A
Try making some fan plots. Test out the `cax` option, `tolerance` option when specifying `scan_index` by a datetime object, passing in an `ax` that is already a cartopy projection, and anything else you think is prudent.
> Lots of little changes to customize Fan plots.

- pydarn/__init__.py
- pydarn/plotting/fan.py
- pydarn/plotting/rtp.py
- pydarn/utils/plotting.py
Somehow, there was a missing right bracket in `fan.py` causing pydarn to fail on import. This fixes.
> Fix: Embargo open bracket typo

- pydarn/plotting/acf.py
- pydarn/plotting/fan.py
- pydarn/plotting/grid.py
- pydarn/plotting/maps.py
- pydarn/plotting/power.py
- pydarn/plotting/rtp.py
- pydarn/utils/recalculate_elevation.py
Bring in all code review changes from testing the release branch for v4.1.1
**Number of approvals:** 0
> Pull in changes from v4.1.1 release testing

- pydarn/utils/superdarn_radars.py
Updating the Siziwang radar names based on input from PI and seen in: https://agupubs.onlinelibrary.wiley.com/doi/full/10.1029/2024SW004131
**issue:** N/A
One should be enough to double check my typing.
N/A
*Reminder, please check your code is:
- copyrighted (if applicable)
- Appropriate disclaimer added
- Modification line filled in (if applicable)*
> Updating Siziwang radar names
